### ISSUE TITLE
Using command in terminal

### ISSUE THREAD

**Issue by mahmoud-zakria-sociomantic** [khrome/ascii-art#16]
Running some of commands in this page are not working
https://github.com/khrome/ascii-art/blob/master/docs/Terminal.md

like: 
`ascii-art text -s green "some text"`,
`ascii-art art textfiles.com`

Output: `Invalid target`

What am I missing?

**Comment by khrome** [comment]
Thanks for the note, this is caused by some overly greedy format checking on an optional target, adding one more param (EX: `ascii-art text -s green "some text"`) will make it work for now, I'll post a fix shortly. It works correctly in version previous to 1.5 if that helps.

**Comment by khrome** [comment]
Fixed. Working as expected.

**Comment by gregors** [comment]
@khrome thank you!
