### ISSUE TITLE
Hosted API

### ISSUE THREAD

**Issue by chrisvxd** [khrome/ascii-art#18]
Hey @khrome 👋 Thanks for creating such a cool ascii art library.

I'm looking to convert open source libs into SaaS APIs as part of my work with [saasify.sh](https://saasify.sh) and thought ascii-art would be a great fit.

Ideally I'd create an API endpoint to generate ascii art along the lines of

```
https://api.saasify.sh/1/call/dev/ascii-art@latest/art
```

where a JSON payload would build your chain of operations (lifted from [one of your examples](https://github.com/khrome/ascii-art-docs/blob/master/Compositing.md))

```json
{
  "ops": [
    {
      "type": "image",
      "width": 40,
      "url": "https://example.com/Images/initech.png",
      "alphabet": "wide"
    },
    {
      "type": "font",
      "text": "Doom",
      "color": "cyan"
    }
  ]
}
```

We'd love to offer a rate-limited API and reserve most of the profits for you. As an example, we've also worked on converting sindresorhus' [imagemin](http://imagemin.saasify.sh/) and minimaxir's [stylecloud](http://wordcloud.saasify.sh/) to APIs.

Looking forward to hearing your thoughts! Would also be happy to jump on a quick call to discuss.

**Comment by khrome** [comment]
First off, thanks for the appreciation.

Very interesting, indeed I think there's a lightweight usage, for which a web service is perfect. There's also a potential to add options to strip or convert ansi for the web that might be perfect here. 
Happy to discuss on a call.

**Comment by chrisvxd** [comment]
Thanks for getting back to me 💪 

Would definitely be good to call early next week. Would you be happy to jump [on our open slack](https://join.slack.com/t/saasify/shared_invite/enQtODAxODA5MzU0NjczLTczOGU3NzNkYTJlMWIwZDkyNjJkOTk3MGEwZThlOWQyNTQxODZjZTExNjAzODJlZDQ3MWM5NWQwMGRiMDcyZTY)? We can arrange a call from there.

**Comment by khrome** [comment]
Closing.
