### ISSUE TITLE
chalk compatibility

### ISSUE THREAD

**Issue by khrome** [khrome/ascii-art#2]
Many app developers use chalk and colour, support those interfaces for drop-in replacement.

Also clarify how ascii-art supports block formatting without formatter wrapping (showing mangled examples from other popular libs).

**Comment by khrome** [comment]
Now supports chalk.

**Comment by luiguild** [comment]
how to use chalk on output image? it's possible?

**Comment by khrome** [comment]
chalk only supports images insofar as you manually iterate through and apply style code (which is probably not what you want). Chalk is designed for simple string output and the interface adapter `ascii-art` has supports only those use cases. But because the image output is a string it is *possible*, just probably not desirable. I would urge you to check out the already released submodules (which make up the rebuild of `ascii-art`, that I'm currently finalizing for release in the next week) at [ascii-art-image](https://github.com/khrome/ascii-art-image) and [ascii-art-ansi](https://github.com/khrome/ascii-art-ansi) if you need more feature than 1.x provides!
