### ISSUE TITLE
stipple doesn't seem to be supported in non-cli version

### ISSUE THREAD

**Issue by brubsby** [khrome/ascii-art#23]
so i have the call to ascii-art:
```
art.image({
            stippled: true,
            filepath: file,
            threshold: 128,
            width: 32,
            height: 32
          });
```

and when the art is logged to the console it appears like this:
![image](https://user-images.githubusercontent.com/57653502/105390469-b572d080-5bde-11eb-866e-98ee3d0574e9.png)

and when i save to a file it gets rendered in notepad++ as:
![image](https://user-images.githubusercontent.com/57653502/105390601-d5a28f80-5bde-11eb-8464-a68a041380c6.png)

i'm basically trying to put some stippled ascii art in a subtitle file, fwiw.

windows 10, most recent version of ascii-art on npm.

**Comment by khrome** [comment]
seems like your terminal font does not support the braille UTF extension characters. I'll check this out.

**Comment by brubsby** [comment]
Ah, well fwiw it's the windows 10 default command line!

**Comment by brubsby** [comment]
the colors are cool, but for my current project I am just regex removing them, so that doesn't concern me as much. (and a flag to do no ansi colors would be nice as well)

i'm mostly confused as to why it doesn't seem to use braille with these input settings. to work around it i reverse engineered that i needed these settings:
```
art.image({
  posterize: true,
  stippled: true,
  background: true,
  filepath: file,
  threshold: 96,
  width: 32,
  height: 32
});
```

seems like just `stippled: true` should work

**Comment by khrome** [comment]
`posterize` is a special setting which outputs the color to the background and outputs braille characters to get sub-character value accuracy via braille pixels along with full flood coloring. So stippling is already happening, but in black. If I allowed default mode stippling on top of that you'd be setting foreground and background to the same color.

What is the end output effect you want?

Also almost every language has a consise `strip-ansi` module available. I have recommended this module in the past for a non-ansi mode. Presently all the pixel calculations are done in color and palette reduction logic is expensive... It would be much cheaper to do this in 256 level grey (or thresholded to 2 color).

There are no docs, but you can directly access the braille output here: https://github.com/khrome/ascii-art-braille/blob/master/braille.js

There is also another slightly less detailed sub-character mode, `blocks`, which may have slightly better support in text editors

**Comment by khrome** [comment]
Doing some work this week. Is there a feature you wanted out of this other than being able to strip ansi chars?

**Comment by khrome** [comment]
So after enabling ansi stripping, I finally get what the issue is in the OP. So I fixed the issue and here are some examples of the expected behavior from the upcoming changes (2.6)

```js
art.image({
    stippled: true,
    filepath: './node_modules/ascii-art-docs/Images/animal_muppet.jpg',
    width: 32,
    height: 32
}, function(err, result){
    console.log(result);
});
```

![Screen Shot 2021-04-15 at 2 07 12 PM](https://user-images.githubusercontent.com/494527/114940609-51d3fa00-9dff-11eb-9882-c914898bad30.png)

```js
art.image({
    filepath: './node_modules/ascii-art-docs/Images/animal_muppet.jpg',
    width: 32,
    height: 32
}).strip({}, function(err, result){
    console.log(result);
});
```
![Screen Shot 2021-04-15 at 2 08 39 PM](https://user-images.githubusercontent.com/494527/114940746-7def7b00-9dff-11eb-99dc-94b9361859b6.png)

```js
art.image({
    stippled: true,
    filepath: './node_modules/ascii-art-docs/Images/animal_muppet.jpg',
    threshold : 128,
    width: 32,
    height: 32
}, function(err, result){
    console.log(result);
});
```
![Screen Shot 2021-04-15 at 2 31 29 PM](https://user-images.githubusercontent.com/494527/114940828-9790c280-9dff-11eb-9e6f-6052ed8cd645.png)

```js
art.image({
    posterized: true,
    stippled: 'black',
    filepath: './node_modules/ascii-art-docs/Images/animal_muppet.jpg',
    threshold : 20,
    width: 32,
    height: 32
}, function(err, result){
    console.log(result);
});
```
![Screen Shot 2021-04-15 at 3 21 10 PM](https://user-images.githubusercontent.com/494527/114940943-bb540880-9dff-11eb-8ec9-53f19940c575.png)

```js
art.image({
    posterized: true,
    stippled: 'black',
    filepath: './node_modules/ascii-art-docs/Images/animal_muppet.jpg',
    threshold : 20,
    width: 32,
    height: 32
}, function(err, result){
    console.log(result);
});
```
![Screen Shot 2021-04-15 at 3 24 22 PM](https://user-images.githubusercontent.com/494527/114941103-f35b4b80-9dff-11eb-93eb-e10d2921f6b0.png)


These are all slightly different in function. Thanks for catching the defect!

**Comment by khrome** [comment]
Changes are live.
