### ISSUE TITLE
table cuts off column headers when column data is shorter

### ISSUE THREAD

**Issue by aappddeevv** [khrome/ascii-art#4]
Headers are cut short when the data is shorter. So if the header is "Header" but all the data for that column is only 2 characters, the header will cut short to "He".

**Comment by khrome** [comment]
Try the changes on HEAD (just clone the repo). I've got some 256 color changes brewing, plus my color FN isn't stable, so I'm not ready to push it to NPM... but table now has 2 options to help out:

- **justify** : auto expand to the provided width (if table is naturally smaller)
- **includeHeader** : include the header in sizing calculations

Let me know if this works!

**Comment by khrome** [comment]
1.4.3 makes these changes live
