### ISSUE TITLE
Default alphabet error (i18n)

### ISSUE THREAD

**Issue by jdz321** [khrome/ascii-art#5]
I just try the example command in https://github.com/khrome/ascii-art/blob/master/docs/Terminal.md, it shows me an error below

![image](https://user-images.githubusercontent.com/8564681/28954115-59941086-790f-11e7-9da9-28d82eeecbe7.png)

**Comment by khrome** [comment]
perhaps related to localization? what happens when you explicitly use an alphabet with `-a`?

**Comment by jdz321** [comment]
It works...  What could be the cause?  

![image](https://user-images.githubusercontent.com/8564681/28978834-3be18012-797a-11e7-99fc-c65ee05350f7.png)

this tool is interesting and I wanna to fix it 😀

**Comment by khrome** [comment]
I'm going to guess that the default is somehow changed as part of localization... my hint being the undefined entry using a localized string in the list of available alphabets. Thanks for looking at it... let me know if you discover anything!

**Comment by khrome** [comment]
Theoretically this alphabet should have no effect, as it's initialized in main, but only used if images are rendered. probably just poorly handled init logic.

**Comment by khrome** [comment]
the 2.0 architecture changed things around, this *should* not be the case anymore.
